import pandas as pd
from sqlalchemy import create_engine
import urllib
import os
from dotenv import load_dotenv

# 1. Load environment variables (Ensure .env contains correct credentials)
load_dotenv()

# 2. Read files generated by the current pipeline
df_roles = pd.read_csv('dim_role.csv')
df_headcount = pd.read_csv('headcount.csv')

# 3. Azure SQL Credentials
server = os.getenv('DB_SERVER')
database = os.getenv('DB_NAME')
username = os.getenv('DB_USER')
password = os.getenv('DB_PASSWORD')
driver = os.getenv('DB_DRIVER', '{ODBC Driver 18 for SQL Server}')

# 4. Connection String with strict encryption (Driver 18)
connection_string = f"DRIVER={driver};SERVER={server};DATABASE={database};UID={username};PWD={password};Encrypt=yes;TrustServerCertificate=yes;"
params = urllib.parse.quote_plus(connection_string)
engine = create_engine(f"mssql+pyodbc:///?odbc_connect={params}")

# 5. Upload tables to database
print("Uploading dim_role to Azure SQL...")
df_roles.to_sql('dim_role', engine, if_exists='replace', index=False)

print("Uploading headcount to Azure SQL...")
df_headcount.to_sql('headcount', engine, if_exists='replace', index=False)

print("Data successfully loaded into Azure SQL Database!")